### ISSUE TITLE
STABO ACE Menu

### ISSUE THREAD

**Issue by TDeakin1013** [gerard-sog/arma3-macvsog-columbia-scripts#149]
Add to ACE actions - ideally into the same section as fast roping. See if we can use an ACE action for the sandbag with timer.

**Comment by Kayoshu** [comment]
Easy to do for actions done from the chopper (deploy stabo, drop stabo)
Harder for action on the dropped sandbag

**Comment by gerard-sog** [comment]
Will not do it
