### ISSUE TITLE
Add requirement for mast to be nearby for triangulation

### ISSUE THREAD

**Issue by TDeakin1013** [gerard-sog/arma3-macvsog-columbia-scripts#152]

**Comment by TDeakin1013** [comment]
https://github.com/gerard-sog/arma3-macvsog-columbia-scripts/pull/160

**Comment by TDeakin1013** [comment]
https://github.com/gerard-sog/arma3-macvsog-columbia-scripts/pull/169

**Comment by gerard-sog** [comment]
Will be done in : https://github.com/gerard-sog/arma3-macvsog-columbia-scripts/pull/178
