### ISSUE TITLE
Make Tracker Module use custom list of AI to spawn. 

### ISSUE THREAD

**Issue by TDeakin1013** [gerard-sog/arma3-macvsog-columbia-scripts#153]
Like that we can have make it spawn VC, NVA, Pathet Lao, etc. and not ONLY NVA.

**Comment by gerard-sog** [comment]
❌ Not possible without a mod overriding classes CfgTrackerArmies.

- https://github.com/gerard-sog/arma3-macvsog-columbia-scripts/pull/163
