### ISSUE TITLE
Multiple screams when mace trap hits someone.

### ISSUE THREAD

**Issue by gerard-sog** [gerard-sog/arma3-macvsog-columbia-scripts#173]
- When mace kill someone on dedicated (and screams are ON), multiple screams instead of 1 happens.
- Also some actions to not need to be REMOTE_EXEC, maybe this is causing multiple screams.

**Comment by Kayoshu** [comment]
Almost certain it's because multiple remoteExec not needed, most of commands for object cretion/animation are global, and can only be called server-side
Will look into that functions next week

**Comment by TDeakin1013** [comment]
Also possible clashing with our inbuilt scream mod, Kay is probably right but in case that isn't the reason

**Comment by gerard-sog** [comment]
Temporary fix: Disable screaming in the addons option

**Comment by gerard-sog** [comment]
fixed in https://github.com/gerard-sog/arma3-macvsog-columbia-scripts/pull/202
