### ISSUE TITLE
Emergency radio bug

### ISSUE THREAD

**Issue by gerard-sog** [gerard-sog/arma3-macvsog-columbia-scripts#195]
talking on emergency radio uses battery of main radio

**Comment by gerard-sog** [comment]
Cannot replicate.

**Comment by TDeakin1013** [comment]
Steps to recreate

Spawn with standard RTO loadout
Transmit on 77 once to initialise
Transmit many times on 343 (this should not effect radio of 77 at all)
Radio of 77 will now be empty

**Comment by gerard-sog** [comment]
To be more complete:
- the above steps will empty the PRC-77 radio
- but the 343 radio will still allow transmission

**Comment by gerard-sog** [comment]
Fixed in https://github.com/gerard-sog/arma3-macvsog-columbia-scripts/pull/204
