### ISSUE TITLE
Trap release audio executed on all players instead of player near trap

### ISSUE THREAD

**Issue by gerard-sog** [gerard-sog/arma3-macvsog-columbia-scripts#216]

**Comment by Kayoshu** [comment]
Still open or is it solved ? (as I'm looking into the traps code atm)

**Comment by gerard-sog** [comment]
Check players near trap and send audio to player only near trap.

**Comment by Kayoshu** [comment]
As specified in wiki, if 4th param soundPosition is used, then soundSource (2nd) is ignored
but you need to get ATL pos or sound is underground (maybe that was the problem using distance param)

https://github.com/gerard-sog/arma3-macvsog-columbia-scripts/commit/fb1d9cc3bd80959d5205026f4e89d658b1f59b77
