### ISSUE TITLE
Script to have Pointman be able to climb in tree

### ISSUE THREAD

**Issue by TDeakin1013** [gerard-sog/arma3-macvsog-columbia-scripts#231]
IRL, some indig soldier would climb trees to see where the enemy was and/or to spot LZ. I think having the Pointman be able to do that would be a nice feature for dense vegetation map maybe ?

**Comment by TDeakin1013** [comment]
https://community.bistudio.com/wiki/nearestTerrainObjects

**Comment by gerard-sog** [comment]
Added in https://github.com/gerard-sog/arma3-macvsog-columbia-scripts/pull/245 
- requires a specific role (based on name + is configurable)
- requires an item (is configurable)
- takes a duration to climb up and down (both values configurable configurable)
