### ISSUE TITLE
Day/Night fixed time acceleration

### ISSUE THREAD

**Issue by TDeakin1013** [gerard-sog/arma3-macvsog-columbia-scripts#253]
Have a script that fixes time acceleration so we have more multi-day operations. 

Say that first light is 6:00 and last light is 18:00

Between 6:00 and 17:30 time is 12x speed (so roughly 1 hour real time)

Between 17:30 and 18:00 time is 6x speed (to give 5 minutes to set up RON position when there is still light)

Between 18:00 and 6:00 time is 144x speed (so night is 5 minutes long)

**Comment by TDeakin1013** [comment]
Idea from Kay

could be a https://cbateam.github.io/CBA_A3/docs/files/common/fnc_waitAndExecute-sqf.html
every second watching sunOrMoon and when it's changing, changing acceleration accordly

**Comment by gerard-sog** [comment]
done in https://github.com/gerard-sog/arma3-macvsog-columbia-scripts/pull/255
